name: Action to deploy your model to an AML endpoint

on: [issue_comment]

jobs:
  # This workflow contains an option profiling job, a test job and a prod/dev deployment job
  train:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/deploy"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: clone branch of PR
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@master
        with:
          ref: ${{ steps.prcomm.outputs.SHA }}

      # Connect or Create the Azure Machine Learning Workspace
      - name: Connect/Create Azure Machine Learning Workspace
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        id: aml_workspace
        uses: Azure/aml-workspace@master
        with:
            azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Profile your model (this is optional)
      # - name: Profile Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_profile
      #   uses: Azure/aml-profile@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Test your model (this is optional)
      - name: Test Model
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        id: aml_test
        uses: Azure/aml-deploy@master
        with:
            azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy your model to dev (this is optional)
      # - name: Dev Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_dev_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Deploy your model to production
      # - name: Prod Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_prod_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}