name: Action to deploy your model to an AML endpoint

on: [issue_comment]

jobs:
  # This workflow contains an option profiling job, a test job and a prod/dev deployment job
  train:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commands: deploy
          permission: admin
          issue-type: pull-request
          named-args: true

      - name: Output command and named arguments
        run: |
          echo ${{ github.event.client_payload.slash_command.command }}
          echo ${{ github.event.client_payload.slash_command.profile }}
          echo ${{ github.event.client_payload.slash_command.test }}
          echo ${{ github.event.client_payload.slash_command.dev }}
          echo ${{ github.event.client_payload.slash_command.prod }}

      # # Connect or Create the Azure Machine Learning Workspace
      # - name: Connect/Create Azure Machine Learning Workspace
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_workspace
      #   uses: Azure/aml-workspace@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Profile your model (this is optional)
      # - name: Profile Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_profile
      #   uses: Azure/aml-profile@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Test your model (this is optional)
      # - name: Test Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_test
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy your model to dev (this is optional)
      # - name: Dev Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_dev_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Deploy your model to production
      # - name: Prod Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_prod_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}