name: aml-deploy

on:
  issue_comment:
    types: [created]

jobs:
  # This workflow contains an option profiling job, a test job and a prod/dev deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slash Command Dispatch
        id: slash_command
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: deploy
          reaction-type: hooray
          permission: write
          issue-type: pull-request
          named-args: true

      - name: Output command and named arguments
        run: |
          echo ${{ github.event }}

      # # Connect or Create the Azure Machine Learning Workspace
      # - name: Connect/Create Azure Machine Learning Workspace
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_workspace
      #   uses: Azure/aml-workspace@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Profile your model (this is optional)
      # - name: Profile Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_profile
      #   uses: Azure/aml-profile@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Test your model (this is optional)
      # - name: Test Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_test
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy your model to dev (this is optional)
      # - name: Dev Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_dev_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Deploy your model to production
      # - name: Prod Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_prod_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}