name: aml-deploy

on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      # # Connect or Create the Azure Machine Learning Workspace
      # - name: Connect/Create Azure Machine Learning Workspace
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_workspace
      #   uses: Azure/aml-workspace@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Profile your model (this is optional)
      # - name: Profile Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_profile
      #   uses: Azure/aml-profile@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Test your model (this is optional)
      # - name: Test Model
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_test
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy your model to dev (this is optional)
      # - name: Dev Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_dev_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Deploy your model to production
      # - name: Prod Deploy
      #   if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #   id: aml_prod_deploy
      #   uses: Azure/aml-deploy@master
      #   with:
      #       azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}