name: slash-command

on:
  issue_comment:
    types: [created]

jobs:
  # This workflow contains an option profiling job, a test job and a prod/dev deployment job
  slash_command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        id: slash_command
        uses: peter-evans/slash-command-dispatch@v1.1.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: deploy
          reaction-type: hooray
          permission: write
          issue-type: pull-request
          named-args: true